version: "3.8"
services:
  app:
    build: .
    image: cruftbot_app
    command: ./scripts/serve
    depends_on:
      - db
    volumes:
      - .:/app
      - user:/root/.cache
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=cruftbot.settings.development
      - PYTHONPATH=/app/
      - PYTHONUNBUFFERED=1
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cruftbot
      POSTGRES_USER: cruftbot
      POSTGRES_PASSWORD: cruftbot
volumes:
  user:
  db:
