version: "3.8"
services:
  app:
    build: .
    image: cruftbot_app
    command: ./scripts/serve
    depends_on:
      - db
    volumes:
      - .:/app
      - user:/root/.cache
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      - DJANGO_SETTINGS_MODULE=cruftbot.settings.development
      - PYTHONPATH=/app/
      - PYTHONUNBUFFERED=1
      - CRUFTBOT_SECRET_KEY=qo!-i61otd!-z7f)erygb4!*8%zt7z10xh=n=^n64&46t_vgf)
      - CRUFTBOT_DEBUG=True
      - CRUFTBOT_SITE_ID=1
      - CRUFTBOT_DATABASE_URL=psql://cruftbot:cruftbot@db:5432/cruftbot
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cruftbot
      POSTGRES_USER: cruftbot
      POSTGRES_PASSWORD: cruftbot
volumes:
  user:
  db:
