#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

echo "==> Running pre-commit…"
poetry run pre-commit run --all-files --show-diff-on-failure

echo "==> Running pyupgrade…"
git ls-files '*.py' | xargs poetry run pyupgrade --py38-plus

echo "==> Running reorder-python-imports…"
git ls-files '*.py' | xargs poetry run reorder-python-imports --py38-plus

echo "==> Running docformatter…"
git ls-files '*.py' | xargs poetry run docformatter --check --wrap-summaries 88 --wrap-descriptions 88 --blank

echo "==> Running black…"
poetry run black --check --quiet .

echo "==> Running flake8…"
poetry run flake8 .

echo "==> Running bandit…"
poetry run bandit -r cruftbot/

# @todo #46 Run pdd locally.
