#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

echo "==> Running pre-commit…"
poetry run pre-commit run --all-files --show-diff-on-failure

# @todo #44 Setup pyupgrade.
# @todo #44 Setup reorder-python-imports.
# @todo #44 Setup docformatter.

echo "==> Running black…"
poetry run black --check --quiet .

# @todo #44 Setup flake8.
# @todo #44 Setup bandit.
