#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

echo "==> Installing python dependencies…"
poetry install

echo "==> Installing ruby dependencies…"
bundle install

echo "==> Installing node dependencies…"
npm install
