#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

echo "==> Running check framework…"
poetry run django-admin check --deploy --fail-level WARNING

echo "==> Running tests…"
poetry run coverage run -m django test

echo "==> Running coverage report…"
poetry run coverage report --fail-under 100
