name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
# @todo #44 Run scripts on continuous integration.

# @todo #155 Add UsePythonVersion@0 task.

# @todo #155 Add UseRubyVersion@0 task.

# @todo #155 Add NodeTool@0 task.
