---
name: test
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
      - uses: actions/setup-node@v2
        with:
          node-version: 15.11.0
      - run: curl -fsSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python  # yamllint disable-line
      - run: echo "${HOME}/.poetry/bin" >> ${GITHUB_PATH}
      - run: ./scripts/install
      - run: ./scripts/check
      # @todo #44 Run test script.
